name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - uses: satackey/action-docker-layer-caching@v0.0.11

      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          cache: "pip"
      - run: pip install -r requirements.txt

      - name: Parse
        run: python parse.py

      - name: Purge Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CF_PURGE_TOKEN }}" \
            -H "Content-Type:application/json" \
            --data '{"purge_everything":true}'

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.13
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.101.0"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy_To_CF_Pages
        uses: cloudflare/wrangler-action@2.0.0
        with:
          command: pages publish ./public --project-name=hugo-obsidian
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      #     publish_branch: master  # deploying branch
