name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Parse
        run: mv parse.sh content; cd content; bash parse.sh
      
      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.13
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy_To_CF_Pages
        uses: cloudflare/wrangler-action@2.0.0
        with:
          command: pages publish ./public --project-name=hugo-obsidian
          apiKey: ${{ secrets.CF_API_KEY }}
          email: ${{ secrets.CF_EMAIL }}
          # apiToken: ${{ secrets.CF_API_TOKEN }}
          # workingDirectory: './public'
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      #     publish_branch: master  # deploying branch
